name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-api:
    runs-on: self-hosted
    steps:

      - name: GHCR Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check out code
        uses: actions/checkout@v3

      - name: Build and push the ODW API Docker image
        run: | 
          docker build . --file docker/api/Dockerfile --tag ghcr.io/open-data-warehouse/odw-api:latest
          docker push ghcr.io/open-data-warehouse/odw-api:latest

  build-celery:
    runs-on: self-hosted
    steps:

      - name: GHCR Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check out code
        uses: actions/checkout@v3

      - name: Build and push the ODW Celery Docker image
        run: | 
          docker build . --file docker/celery/Dockerfile --tag ghcr.io/open-data-warehouse/odw-celery:latest
          docker push ghcr.io/open-data-warehouse/odw-celery:latest


